import{a as h,i as u,S as y}from"./assets/vendor-D5mnuR-h.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g="48859120-c5edc5c574d1328ed42f58f74",L="https://pixabay.com/api/";async function m(i,a=1,s=40){try{const r=await h.get(L,{params:{key:g,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:a}});return r.data.hits.length?{hits:r.data.hits,totalHits:r.data.totalHits}:{hits:[],totalHits:0}}catch(r){return u.error({title:"Error",message:"Failed to fetch images. Try again!"}),console.error("Fetch error:",r),{hits:[],totalHits:0}}}let f;function p(i,a=!1){const s=document.querySelector(".gallery");if(!s)return;a||(s.innerHTML="");const r=i.map(({webformatURL:e,largeImageURL:t,tags:o,likes:d,views:n,comments:l,downloads:c})=>`<a href="${t}" class="gallery-item">
            <img src="${e}" alt="${o}" />
            <div class="info">
                <p><span class="label">Likes:</span> ${d}</p>
                <p><span class="label">Views:</span> ${n}</p>
                <p><span class="label">Comments:</span> ${l}</p>
                <p><span class="label">Downloads:</span> ${c}</p>
            </div>
        </a>`).join("");s.insertAdjacentHTML("beforeend",r),f||(f=new y(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})),f.refresh()}document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector("#search-form"),a=document.querySelector(".gallery"),s=document.querySelector("#load-more"),r=document.querySelector(".loader");let e="",t=1;const o=40;let d=null;if(!i||!a||!s||!r){console.error("Не все элементы доступны для привязки событий.");return}i.addEventListener("submit",async n=>{if(n.preventDefault(),e=n.target.elements.searchQuery.value.trim(),!e){u.warning({title:"Warning",message:"Please enter a search term!"});return}t=1,a.innerHTML="",s.classList.add("hidden"),r.classList.remove("hidden");const{hits:l,totalHits:c}=await m(e,t,o);if(r.classList.add("hidden"),l.length===0){u.error({message:"No images found. Try again!"});return}p(l),o<c&&s.classList.remove("hidden")}),s.addEventListener("click",async()=>{d=document.querySelector(".gallery-item:last-of-type"),t+=1,r.classList.remove("hidden");const{hits:n,totalHits:l}=await m(e,t,o);r.classList.add("hidden"),p(n,!0),setTimeout(()=>{if(d){const c=d.nextElementSibling;c&&c.scrollIntoView({behavior:"smooth",block:"start"})}},300),t*o>=l&&(s.classList.add("hidden"),u.info({message:"We're sorry, but you've reached the end of search results."}))})});
//# sourceMappingURL=index.js.map
