import{a as p,S as L,i as c}from"./assets/vendor-mYwBqgd4.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();p.defaults.baseURL="https://pixabay.com";async function u(t,a){const n="https://pixabay.com/api/",i={key:"48901588-d5168312fb6e442ccb66c926a",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:40};return await p.get(n,{params:i})}const d=new L(".gallery a",{captionsData:"alt",captionDelay:250});function b({webformatURL:t,largeImageURL:a,tags:n,likes:i,views:e,comments:r,downloads:l}){return`<li class="gallery-item">
    <a class="gallery-link" href="${a}">
      <img class="gallery-image" src="${t}" alt="${n}" />
    </a>
    <ul class="image-info">
      <li class="info-item"><p class="text">Likes</p><p class="text-value">${i}</p></li>
      <li class="info-item"><p class="text">Views</p><p class="text-value">${e}</p></li>
      <li class="info-item"><p class="text">Comments</p><p class="text-value">${r}</p></li>
      <li class="info-item"><p class="text">Downloads</p><p class="text-value">${l}</p></li>
    </ul>
  </li>`}function f(t){return t.map(b).join("")}const s={form:document.querySelector(".search-form"),input:document.querySelector("#image-input"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".js-load-btn"),loader:document.querySelector(".js-loader")},o={query:"",page:1,total:null,per_page:40};s.form.addEventListener("submit",async t=>{if(t.preventDefault(),o.query=s.input.value.trim(),!o.query){c.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}s.gallery.innerHTML="",s.form.reset(),g(),h();try{const{data:a}=await u(o.query,o.page,o.per_page);a.hits.length===0?c.info({message:"Sorry, no images found. Try again!",backgroundColor:"#ef4040",messageColor:"#fafafb",position:"topRight"}):(s.gallery.innerHTML=f(a.hits),d.refresh(),o.total=a.totalHits,m())}catch{c.error({title:"Error",message:"Something went wrong. Try again.",position:"topRight"})}finally{y()}});s.btnLoadMore.addEventListener("click",async()=>{o.page+=1,h();try{const{data:t}=await u(o.query,o.page,o.per_page);s.gallery.insertAdjacentHTML("beforeend",f(t.hits)),d.refresh(),m(),v()}catch{c.error({title:"Error",message:"Something went wrong. Try again.",position:"topRight"})}finally{y()}});function w(){s.btnLoadMore.classList.remove("hidden")}function g(){s.btnLoadMore.classList.add("hidden")}function m(){const t=Math.ceil(o.total/o.per_page);o.page>=t?(g(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}function h(){s.loader.classList.remove("hidden")}function y(){s.loader.classList.add("hidden")}function v(){const{height:t}=s.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
